[features]
resolution = true
skip-lint = false

[programs.localnet]
predictsol_sc = "Fhud5X7RHZT6159Mr964dhZA6SUDj5Dt8Zk54K4x6Twf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/predictsol_mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"
