[features]
resolution = true
skip-lint = false

[programs.localnet]
predictsol_sc = "BNn1nkWfB99z9b515Bk6aC5sDexX1Hf5BpfTL1zr7gtG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/predictsol_devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"
